# Generated by Django 6.0 on 2026-01-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
