# Generated by Django 6.0 on 2026-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_product_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_units',
            field=models.IntegerField(default=0),
        ),
    ]
